# -*- coding: utf-8 -*-
"""ethereum_fraud_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HlSNVbSsuUa8BJFT6xfut7msXnCJg6NR
"""

from google.colab import files
uploaded = files.upload()

"""### Load libraries"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler, LabelEncoder
from sklearn.model_selection import train_test_split, RandomizedSearchCV
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report, confusion_matrix
from imblearn.combine import SMOTEENN
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Conv1D, MaxPooling1D, Flatten
from tensorflow.keras.optimizers import Adam
import xgboost as xgb
import warnings
warnings.filterwarnings('ignore')

# Random seeds for reproducibility
np.random.seed(42)
tf.random.set_seed(42)

"""### Load the dataset"""

data = pd.read_csv("transaction_dataset.csv")
print(f"Dataset shape: {data.shape}")
print(f"Number of features: {data.shape[1] - 1}")
print(f"Fraud rate: {data['FLAG'].mean():.3f}")
print(f"Missing values: {data.isnull().sum().sum()}")
data.columns = data.columns.str.strip().str.replace(r'\b\s+\b', '_', regex=True)
data.columns

"""### Exploratory Data Analysis"""

# Show number of values in each class in percent
data['FLAG'].value_counts(normalize=True) * 100

data.drop(columns=['Unnamed: 0', 'Index', 'Address'], axis=0, inplace=True)
numeric = data.select_dtypes(include=['number']).columns
constant_var = [i for i in numeric if data[i].var() == 0]
print(f"Number of features that have constant value is {len(constant_var)}")
data.drop(columns=constant_var, axis=0, inplace=True)

categories = data.select_dtypes(include=['object']).columns

print(f"Number of rows that has at least one missing value: {data.isnull().any(axis=1).sum()}")
missing_mask = data.isnull().any(axis=1)

plt.figure(figsize=(10, 7))
numeric = data.select_dtypes(include=['number']).columns
corr = data[numeric].corr()
mask = np.zeros_like(corr)
mask[np.triu_indices_from(mask)] = True
sns.heatmap(corr, mask=mask, annot=False, vmin=-1, vmax=1)
plt.show()

# Class distribution plot
plt.figure(figsize=(15, 10))
plt.subplot(2, 3, 1)
sns.countplot(x='FLAG', data=data)
plt.title('Class Distribution')
plt.xlabel('Fraud Label (0=Legitimate, 1=Fraudulent)')
plt.ylabel('Count')

"""### Feature Engineering"""

print("Encoding categorical variables...")
le = LabelEncoder()
df = data.copy()
for col in categories:
        if col in df.columns:
            df[col] = le.fit_transform(df[col].astype(str))

print("Performing feature selection...")
numeric_features = df.select_dtypes(include=[np.number]).drop('FLAG', axis=1)
correlations = numeric_features.corrwith(df['FLAG']).abs()

selected_features = correlations[correlations > 0.1].index.tolist()

if len(selected_features) < 5:
    selected_features = correlations.nlargest(10).index.tolist()

print(f"Selected {len(selected_features)} features based on correlation analysis")
print(f"Selected features: {selected_features}")

# Prepare feature matrix and target
X = df[selected_features]
y = df['FLAG']

# Scaling features using MinMaxScaler
print("Scaling features...")
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)

# Cube root transformation
print("Applying cube root transformation...")
X_cbrt = np.cbrt(X_scaled)

print(f"Final feature matrix shape: {X_cbrt.shape}")
print(f"Class distribution: {y.value_counts().to_dict()}")

def split_and_resample_data(X, y):
    """Split data and apply SMOTE+ENN for handling class imbalance"""
    print("\n4. DATA SPLITTING AND RESAMPLING")

    # Split data into train and test sets
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.3, random_state=42, stratify=y
    )

    X_train = X_train.to_numpy()
    X_test = X_test.to_numpy()
    y_train = y_train.to_numpy()
    y_test = y_test.to_numpy()

    print(f"Training set size: {X_train.shape[0]}")
    print(f"Test set size: {X_test.shape[0]}")
    print(f"Original training class distribution: {pd.Series(y_train).value_counts().to_dict()}")

    # SMOTEENN for handling class imbalance
    print("Applying SMOTE + ENN resampling...")
    sm = SMOTEENN(random_state=42)
    X_train_resampled, y_train_resampled = sm.fit_resample(X_train, y_train)

    print(f"Resampled training set size: {X_train_resampled.shape[0]}")
    print(f"Resampled class distribution: {pd.Series(y_train_resampled).value_counts().to_dict()}")

    return X_train_resampled, X_test, y_train_resampled, y_test

X_train, X_test, y_train, y_test = split_and_resample_data(X,y)

"""### Training the Machine learning models"""

# 5. MODEL IMPLEMENTATIONS

class FraudDetectionModels:
    """Class containing all ML models for fraud detection"""

    def __init__(self):
        self.models = {}
        self.predictions = {}
        self.results = {}

    def train_neural_network(self, X_train, y_train, X_test):
        """Neural Network (MLP) implementation"""
        print("\nTraining Neural Network...")

        model = Sequential([
            Dense(128, activation='relu', input_shape=(X_train.shape[1],)),
            Dropout(0.2),
            Dense(64, activation='relu'),
            Dropout(0.2),
            Dense(32, activation='relu'),
            Dropout(0.2),
            Dense(1, activation='sigmoid')
        ])

        model.compile(
            optimizer=Adam(learning_rate=0.001),
            loss='binary_crossentropy',
            metrics=['accuracy']
        )

        # Model training
        history = model.fit(
            X_train, y_train,
            epochs=50,
            batch_size=32,
            validation_split=0.2,
            verbose=0
        )

        # Predictions
        y_pred_proba = model.predict(X_test, verbose=0)
        y_pred = (y_pred_proba > 0.5).astype(int).flatten()

        self.models['Neural Network'] = model
        self.predictions['Neural Network'] = y_pred

        return y_pred

    def train_cnn(self, X_train, y_train, X_test):
        """Convolutional Neural Network implementation"""
        print("Training CNN...")

        # Reshape data for CNN (add sequence dimension)
        X_train_cnn = X_train.reshape(X_train.shape[0], X_train.shape[1], 1)
        X_test_cnn = X_test.reshape(X_test.shape[0], X_test.shape[1], 1)

        model = Sequential([
            Conv1D(64, 3, activation='relu', input_shape=(X_train.shape[1], 1)),
            MaxPooling1D(2),
            Conv1D(32, 3, activation='relu'),
            MaxPooling1D(2),
            Flatten(),
            Dense(64, activation='relu'),
            Dropout(0.2),
            Dense(1, activation='sigmoid')
        ])

        model.compile(
            optimizer=Adam(learning_rate=0.001),
            loss='binary_crossentropy',
            metrics=['accuracy']
        )

        # Train the model
        history = model.fit(
            X_train_cnn, y_train,
            epochs=50,
            batch_size=32,
            validation_split=0.2,
            verbose=0
        )

        # Make predictions
        y_pred_proba = model.predict(X_test_cnn, verbose=0)
        y_pred = (y_pred_proba > 0.5).astype(int).flatten()

        self.models['CNN'] = model
        self.predictions['CNN'] = y_pred

        return y_pred

    def train_decision_tree(self, X_train, y_train, X_test):
        """Decision Tree implementation"""
        print("Training Decision Tree...")

        model = DecisionTreeClassifier(
            max_depth=10,
            random_state=42,
            class_weight='balanced'
        )

        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)

        self.models['Decision Tree'] = model
        self.predictions['Decision Tree'] = y_pred

        return y_pred

    def train_random_forest(self, X_train, y_train, X_test):
        """Random Forest implementation with hyperparameter tuning"""
        print("Training Random Forest...")

        # Hyperparameter tuning
        param_distributions = {
            'n_estimators': [50, 100, 200],
            'max_depth': [10, 20, None],
            'min_samples_split': [2, 5, 10],
            'min_samples_leaf': [1, 2, 4]
        }

        rf = RandomForestClassifier(random_state=42, class_weight='balanced')

        # RandomizedSearchCV for hyperparameter tuning
        rf_random = RandomizedSearchCV(
            estimator=rf,
            param_distributions=param_distributions,
            n_iter=10,
            cv=3,
            verbose=0,
            random_state=42,
            n_jobs=-1
        )

        rf_random.fit(X_train, y_train)

        # Use best model
        model = rf_random.best_estimator_
        y_pred = model.predict(X_test)

        print(f"Best RF parameters: {rf_random.best_params_}")

        self.models['Random Forest'] = model
        self.predictions['Random Forest'] = y_pred

        return y_pred

    def train_gradient_boosting(self, X_train, y_train, X_test):
        """Gradient Boosting (XGBoost) implementation"""
        print("Training Gradient Boosting...")

        # Calculate scale_pos_weight for imbalanced data
        scale_pos_weight = (y_train == 0).sum() / (y_train == 1).sum()

        model = xgb.XGBClassifier(
            n_estimators=100,
            learning_rate=0.1,
            max_depth=6,
            scale_pos_weight=scale_pos_weight,
            random_state=42,
            eval_metric='logloss'
        )

        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)

        self.models['Gradient Boosting'] = model
        self.predictions['Gradient Boosting'] = y_pred

        return y_pred

# 5. Train all models
print("TRAINING ML MODELS")

models_obj = FraudDetectionModels()
  # Train each model
models_obj.train_neural_network(X_train, y_train, X_test)
models_obj.train_cnn(X_train, y_train, X_test)
models_obj.train_decision_tree(X_train, y_train, X_test)
models_obj.train_random_forest(X_train, y_train, X_test)
models_obj.train_gradient_boosting(X_train, y_train, X_test)

"""### Evaluate models"""

# 6. MODEL EVALUATION

def evaluate_models(models_obj, y_test):
    """Evaluate all models and return results"""
    print("\n5. MODEL EVALUATION")

    results = {}

    for model_name, y_pred in models_obj.predictions.items():
        accuracy = accuracy_score(y_test, y_pred)
        precision = precision_score(y_test, y_pred, zero_division=0)
        recall = recall_score(y_test, y_pred, zero_division=0)
        f1 = f1_score(y_test, y_pred, zero_division=0)

        results[model_name] = {
            'Accuracy': accuracy,
            'Precision': precision,
            'Recall': recall,
            'F1-Score': f1
        }

        print(f"\n{model_name} Results:")
        print(f"  Accuracy:  {accuracy:.3f}")
        print(f"  Precision: {precision:.3f}")
        print(f"  Recall:    {recall:.3f}")
        print(f"  F1-Score:  {f1:.3f}")

    return results

# Evaluate models
results = evaluate_models(models_obj, y_test)

def plot_results(results):
    """Create comparison plots for model performance"""
    print("\n6. RESULTS VISUALIZATION")
    print("-" * 40)

    # Results converted to DataFrame for easier plotting
    df_results = pd.DataFrame(results).T

    # Subplots for each metric
    fig, axes = plt.subplots(2, 2, figsize=(15, 10))
    fig.suptitle('Model Performance Comparison', fontsize=16)

    metrics = ['Accuracy', 'Precision', 'Recall', 'F1-Score']
    colors = ['blue', 'green', 'red', 'purple', 'orange']

    for i, metric in enumerate(metrics):
        ax = axes[i//2, i%2]
        bars = ax.bar(df_results.index, df_results[metric], color=colors[:len(df_results)])
        ax.set_title(f'Comparison of {metric}')
        ax.set_ylabel(metric)
        ax.set_ylim(0, 1.1)

        # Adding value labels on bars
        for bar in bars:
            height = bar.get_height()
            ax.text(bar.get_x() + bar.get_width()/2., height + 0.01,
                   f'{height:.3f}', ha='center', va='bottom')

        plt.setp(ax.get_xticklabels(), rotation=45, ha='right')

    plt.tight_layout()
    plt.show()

    # Create summary table
    print("\nModel Performance Summary:")
    print("=" * 70)
    print(df_results.round(3))

    # Find best performing model
    best_model = df_results['F1-Score'].idxmax()
    print(f"\nBest performing model: {best_model}")
    print(f"F1-Score: {df_results.loc[best_model, 'F1-Score']:.3f}")

plot_results(results)